### ISSUE TITLE
ダブルクォーテーションに半角と全角が混じっている

### ISSUE THREAD

**Issue by somacells** [RWD-data-environment-in-Hospital/Documents#18]
<role rolename="admin-gui"/> <role rolename=”manager-gui”/> <role rolename=”role1”/> <user username=”tomcat” password=”s3cret” roles="admin-gui,manager-gui”/>
ダブルクォーテーションが半角と全角が混じっているようなので、そのままコピペではうまくいかないようです。
ドキュメント修正をお願いします。

**Comment by kashiwabb** [comment]
ドキュメントを修正しました。
